/**
 * @file Logrotate integration (Unix only)
 * @description Manages logrotate mode: stable log naming, SIGHUP handling,
 *   and system logrotate config generation. Uses the existing servers.json
 *   registry for PIDs — no separate PID files needed.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { userInfo } from 'os';
import { getConfigDir, getConfigPath, getDefaultLogDir, readConfig } from '../config/index.js';

// ─── Platform Gate ───────────────────────────────────────────────────────────

/**
 * Check if the current platform supports logrotate.
 * Throws a descriptive error on unsupported platforms.
 */
export function assertUnixPlatform(): void {
  if (process.platform === 'win32') {
    throw new Error(
      'stw logrotate is only available on Linux/macOS.\n' +
      '   On Windows, use: stw logs --clear',
    );
  }
}

// ─── Enable / Disable / Status ───────────────────────────────────────────────

/**
 * Check if logrotate mode is enabled.
 */
export function isLogrotateEnabled(): boolean {
  const configPath = getConfigPath();
  if (!existsSync(configPath)) return false;

  try {
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    return config.logrotate === true;
  } catch {
    return false;
  }
}

/**
 * Enable logrotate mode (switches to stable log filenames).
 */
export function enableLogrotate(): void {
  const configDir = getConfigDir();
  const configPath = getConfigPath();

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  const config = existsSync(configPath)
    ? JSON.parse(readFileSync(configPath, 'utf8'))
    : {};

  config.logrotate = true;
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf8');
}

/**
 * Disable logrotate mode (switches back to timestamped log filenames).
 */
export function disableLogrotate(): void {
  const configPath = getConfigPath();
  if (!existsSync(configPath)) return;

  const config = JSON.parse(readFileSync(configPath, 'utf8'));
  delete config.logrotate;
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf8');
}

// ─── Config Generation ───────────────────────────────────────────────────────

export interface LogrotateInitOptions {
  /** Use copytruncate strategy instead of postrotate+SIGHUP (default: false) */
  copytruncate?: boolean;
  /** Custom log directory (uses resolved log dir if not provided) */
  logDir?: string;
}

/**
 * Generate the logrotate config file content.
 * Uses resolved paths — nothing hardcoded.
 */
export function generateConfig(options: LogrotateInitOptions = {}): string {
  const config = readConfig();
  const defaultLogDir = config['log-dir'] ?? getDefaultLogDir();
  const logDir = options.logDir ?? defaultLogDir;
  const logGlob = join(logDir, 'stw-*.log');
  const registryPath = join(getConfigDir(), 'servers.json');

  let user: string;
  let group: string;
  try {
    const info = userInfo();
    user = info.username;
    group = info.username;
  } catch {
    user = 'root';
    group = 'root';
  }

  const lines = [
    `# /etc/logrotate.d/swagger-to-wiremock`,
    `# Generated by: stw logrotate --init`,
    `# Strategy: ${options.copytruncate ? 'copytruncate' : 'postrotate + SIGHUP'}`,
    ``,
    `${logGlob} {`,
    `    daily`,
    `    rotate 7`,
    `    compress`,
    `    delaycompress`,
    `    missingok`,
    `    notifempty`,
    `    su ${user} ${group}`,
  ];

  if (options.copytruncate) {
    lines.push(`    copytruncate`);
  } else {
    lines.push(``);
    lines.push(`    postrotate`);
    lines.push(`        jq -r '.[].pid' "${registryPath}" 2>/dev/null | xargs -r kill -HUP || true`);
    lines.push(`    endscript`);
  }

  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Write the logrotate config to a file in the current working directory.
 * Also enables logrotate mode if not already enabled.  
 *
 * @returns { path, content } — path to the generated file, and its content
 */
export function writeLogrotateConfig(options: LogrotateInitOptions = {}): { path: string; content: string } {
  const content = generateConfig(options);
  const outputPath = join(process.cwd(), 'swagger-to-wiremock.logrotate');

  // Auto-enable logrotate mode
  if (!isLogrotateEnabled()) {
    enableLogrotate();
  }

  writeFileSync(outputPath, content, 'utf8');
  return { path: outputPath, content };
}
